
class Tata:
    
    Chairman = "Ratan Tata"

    def _init_(self,company, ceo):
        
        print("Welcome to Tata Groups")
        
        self.company = company
        self.ceo = ceo

    def automobiles(self):

        class TataMotors:

            def __init__(self, brand, bestCar):

                print("Connecting Aspirations")

                self.brand = brand
                self.bestCar = bestCar

            def manufacture(self):

                print("Car will be manufactured at respective workshop.")


            def advertisement(self):

                print("Each brand has its own advertisement")

        jaguar = TataMotors("Jaguar","F-TYPE")
        jaguar.manufacture()
        jaguar.advertisement()

    def IT(self):

        class TCS:

            package = "3.6 LPA"

            def __init__(self, project, projectDuration):

                print("Tata Consultancy Services")

                self.project = project
                self.projectDuration = projectDuration

            def projectResources(self):

                print("All the resources require for the project")

        customer = IT("Amazon Dummy", "3 Months")
        customer.projectResources()

    def revenue(self):

        print("Revenue generated by TATA")

print("Welcome to TATA")


